[package]
name = "key_gen"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bitcoin = "0.19.1"
ethereum_support = { path = "../ethereum_support" }
hex = "0.4"
rand = "0.4"
secp256k1 = { version = "0.12", features = ["rand"] }
tiny-keccak = "1.5.0"
