version: '3'
services:
  trading_service:
    build:
      context: ../..
      dockerfile: Dockerfile_cache
    env_file:
      - ./regtest.env
      - ./network.env
    environment:
      - EXCHANGE_SERVICE_URL=http://exchange_service:8000
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,trading_service=debug,bitcoin_htlc=debug
      - RUST_BACKTRACE=1
    ports:
    - "8000:8000"
    depends_on:
    - exchange_service
    - bitcoin
    command: ./trading_service

  exchange_service:
    build:
      context: ../..
      dockerfile: Dockerfile_cache
    command: bash -c 'sleep 5 && ./exchange_service'
    env_file:
      - ./regtest.env
      - ./network.env
    environment:
      - BITCOIN_RPC_URL=http://bitcoin:18443
      - ETHEREUM_NODE_ENDPOINT=http://ethereum:8545
      - TREASURY_SERVICE_URL=http://treasury_service:8000
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,exchange_service=debug,bitcoin_htlc=debug
      - RUST_BACKTRACE=1
      - BITCOIN_SATOSHI_PER_KB=50
    ports:
    - "8010:8000"
    depends_on:
    - treasury_service
    - ethereum
    command: ./exchange_service

  treasury_service:
    build:
      context: ../..
      dockerfile: Dockerfile_cache
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,fake_treasury_service=debug
      - RATE=0.1
    ports:
    - "8020:8000"
    command: ./fake_treasury_service

  ethereum:
    image: trufflesuite/ganache-cli
    command: -a 7 -m supersecure
    ports:
    - "8545:8545"

  bitcoin:
    image: ruimarinho/bitcoin-core
    logging:
        driver: none
    command:
      -regtest
      -server
      -printtoconsole
      -rpcbind=0.0.0.0:18443
      -rpcauth=bitcoin:cb77f0957de88ff388cf817ddbc7273$$9eaa166ace0d94a29c6eceb831a42458e93faeb79f895a7ee4ce03f4343f8f55
      -rpcallowip=0.0.0.0/0
    ports:
      - "18443:18443"
