version: '3'
services:
#  comit_node_alice:
#    build: ../..
#    env_file:
#      - ./regtest.env
#      - ./network.env
#    environment:
#      - COMIT_NODE_URL=http://comit_node_bob:8000
#      - ROCKET_ADDRESS=0.0.0.0
#      - RUST_LOG=comit_node=debug,bitcoin_htlc=debug
#      - RUST_BACKTRACE=1
#    ports:
#    - "8000:8000"
#    depends_on:
#    - comit_node_bob
#    - bitcoin
#    command: ./comit_node
#
#  comit_node_bob:
#    build: ../..
#    command: bash -c 'sleep 5 && ./comit_node'
#    env_file:
#      - ./regtest.env
#      - ./network.env
#    environment:
#      - BITCOIN_RPC_URL=http://bitcoin:18443
#      - ETHEREUM_NODE_ENDPOINT=http://ethereum:8545
#      - ROCKET_ADDRESS=0.0.0.0
#      - RUST_LOG=comit_node=debug,bitcoin_htlc=debug
#      - RUST_BACKTRACE=1
#      - BITCOIN_SATOSHI_PER_KB=50
#    ports:
#    - "8010:8000"
#    depends_on:
#    - ethereum

  ethereum:
    image: trufflesuite/ganache-cli
    command: -a 7 -m supersecure
    ports:
    - "8545:8545"

  bitcoin:
    image: ruimarinho/bitcoin-core:0.16.3-alpine
    command:
      -regtest
      -server
      -printtoconsole
      -rpcbind=0.0.0.0:18443
      -rpcauth=bitcoin:cb77f0957de88ff388cf817ddbc7273$$9eaa166ace0d94a29c6eceb831a42458e93faeb79f895a7ee4ce03f4343f8f55
      -rpcallowip=0.0.0.0/0
      -debug=1
      -zmqpubrawblock=tcp://*:28332
    ports:
      - "18443:18443"
      - "28332:28332"
