[package]
name = "bitcoin-rpc"
version = "0.1.0"
authors = ["Thomas Eizinger <thomas@eizinger.io>"]

[dependencies]
jsonrpc = { path = "../jsonrpc" }
serde_json = "1.0.16"
serde_derive = "1.0.42"
serde = "1.0.42"
rustc-serialize = "0.3.24"
log = "0.4"

[dev-dependencies]
env_logger = "0.5.9"
