[package]
name = "ledger_query_service"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]

[dependencies]
bitcoin_rpc_client = "0.4"
bitcoin_support = { path = "../../vendor/bitcoin_support" }
byteorder = "1.2"
config = "0.9"
debug_stub_derive = "0.3"
ethereum_support = { path = "../../vendor/ethereum_support" }
http = "0.1"
log = "0.4"
pretty_env_logger = "0.2"
serde = "1"
serde_derive = "1"
url = "1.7"
warp = "0.1"
zmq-rs = "0.1"

[dev-dependencies]
env_logger = "0.5"
hex = "0.3"
rand = "0.3"
secp256k1_support = { path = "../../vendor/secp256k1_support" }
spectral = "0.6"
tc_web3_client = { path = "../../vendor/tc_web3_client" }
testcontainers = "0.3"
