[package]
name = "ledger_query_service"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
rocket = "=0.3.14"
rocket_codegen = "=0.3.14"
rocket_contrib = "=0.3.14"
http-api-problem = { version = "0.7", features = ["with_rocket"] }
bitcoin_support = { path = "../../vendor/bitcoin_support" }

[dev-dependencies]
spectral = "0.6"
pretty_env_logger = "0.2"
http = "0.1"
