[comit]
remote_comit_node_url = "127.0.0.1:8011"
comit_listen = "0.0.0.0:8001"
secret_seed = "f87165e305b0f7c4824d3806434f9d0909610a25641ab8773cf92a48c9d77670"

[http_api]
address="0.0.0.0"
port=8000
logging=true

[ledger_query_service]
url = "http://localhost:8080"
[ledger_query_service.bitcoin]
poll_interval_secs = 1
[ledger_query_service.ethereum]
poll_interval_secs = 1
