pull_request_rules:
  - name: merge on CI success and one approval
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=blocked
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
      delete_head_branch:
