pull_request_rules:
  - name: instruct bors to merge dependabot PRs with passing tests
    conditions:
      - "author=dependabot-preview[bot]"
      - "status-success=ci/circleci: debug-build-test"
    actions:
      comment:
        message: "bors r+"
  - name: instruct bors to merge PRs with passing tests and 2 approvals
    conditions:
      - "#approved-reviews-by>=2"
      - "status-success=ci/circleci: debug-build-test"
      - "status-success=license/cla"
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
    actions:
      comment:
        message: "bors r+"
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
    actions:
      delete_head_branch:
