pull_request_rules:
  - name: instruct bors to merge dependabot PRs with passing tests
    conditions:
      - "author=dependabot[bot]"
      - "status-success=static_analysis"
      - "-status-failure~=^build"
      - label!=no-mergify
    actions:
      comment:
        message: "bors r+"
  - name: instruct bors to merge PRs with passing tests and 2 approvals
    conditions:
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "status-success=static_analysis"
      - "-status-failure~=^build"
      - -conflict
      - label!=work-in-progress
      - label!=blocked
      - label!=no-mergify
      - head~=^(?!release.*).*$
      - base=dev
    actions:
      comment:
        message: "bors r+"
  - name: Delete branch if the pull request is merged
    conditions:
      - merged
      - head~=^(?!release.*).*$
    actions:
      delete_head_branch:
        force: false
  - name: Block regular PRs from merging into master
    conditions:
      - base=master
      - head~=^(?!release.*).*$
    actions:
      close:
        message: This repository is using GitFlow. New features should be merged into `dev` instead of master. Please open a new pull request that targets `dev` instead.
