language: rust
cache: cargo
sudo: required
env:
  global:
  - BITCOIN_RPC_URL="http://localhost:18443"
  - BITCOIN_RPC_USERNAME="bitcoin"
  - BITCOIN_RPC_PASSWORD="54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg="
rust: nightly-2018-05-05
install: true
services:
  - docker
before_script:
- "./setup.sh"
script:
- "./check-fmt.sh"
- cargo build --verbose
- ./run_tests.sh
notifications:
  email: false
  slack:
    rooms:
      - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-swap-bots
    on_success: always
    on_failure: always
    on_pull_requests: true
