language: rust
cache:
  yarn: true
  directories:
  - "$HOME/.cargo"
  - "$HOME/.cache/sccache"
  - "$TRAVIS_BUILD_DIR/api_tests/node_modules"
sudo: required
rust: nightly-2018-12-06
addons:
  apt:
    sources:
    - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
      key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - libzmq3-dev
    - yarn
install: true
services: docker
before_script:
- which cargo-make || cargo install --debug cargo-make
- nvm install 11
script: cargo make travis
notifications:
  email: false
  slack:
    rooms:
    - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-bots
    on_success: never
    on_failure: always
    on_pull_requests: true
