language: rust
cache:
  directories:
  - "$HOME/.cargo"
  - "$HOME/.cache/sccache"
  - "$TRAVIS_BUILD_DIR/api_tests/node_modules"
sudo: required
rust: nightly-2018-11-13
addons:
  apt:
    packages:
    - libzmq3-dev
install: true
services: docker
before_script: which cargo-make || cargo install --debug cargo-make
script: cargo make travis
notifications:
  email: false
  slack:
    rooms:
    - tenx-company:buMm6Pg6Sbhljx2HRLwNC44z#coblox-bots
    on_success: never
    on_failure: always
    on_pull_requests: true
