language: rust
cache: cargo
env:
  global:
    - BITCOIN_RPC_URL="http://localhost:18443"
    - BITCOIN_RPC_USERNAME="bitcoin"
    - BITCOIN_RPC_PASSWORD="54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg="
rust: nightly-2018-05-05
install: true # Install would run cargo build again - we don't need that
before_script:
  - ./install-rust-fmt.sh
  - .docker/bitcoind-regtest
script:
  - ./check-rust-fmt.sh
  - cargo build --verbose
  - cargo test --verbose