language: rust
cache: cargo
env:
  global:
    - BITCOIN_RPC_URL="http://localhost:18443"
    - BITCOIN_RPC_USERNAME="bitcoin"
    - BITCOIN_RPC_PASSWORD="54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg="
rust: nightly-2018-05-05
install: true # Install would run cargo build again - we don't need that
before_script:
  - ./setup.sh
  - .docker/bitcoind-regtest
script:
  - ./check-fmt.sh
  - cargo build --verbose

  # Bitcoin-RPC has integration tests with a bitcoin node. Those MUST run sequentially.
  - cargo test --verbose --all --exclude bitcoin-rpc
  - cargo test --verbose --all --package bitcoin-rpc --jobs 1 