[package]
name = "nectar"
version = "0.1.0"
authors = ["CoBloX Team <team@coblox.tech>"]
edition = "2018"

[dependencies]
anyhow = "1"
async-trait = "0.1"
bitcoin = "0.23.0"
chrono = "0.4"
cnd = { git = "https://github.com/comit-network/comit-rs", package = "cnd", branch = "nectar" }
comit = { git = "https://github.com/comit-network/comit-rs", package = "comit", branch = "nectar" }
futures = "0.3.5"
reqwest = "0.10.6"

[dev-dependencies]
testcontainers = "0.9"
tokio = { version = "0.2.21", features = ["macros"] }
