[workspace]

members = [
    "btc_htlc",
	"jsonrpc",
	"trading_service",
	"exchange_service",
	"trading_client",
	"fake_treasury_service",
	"common_types",
	"bitcoin_rpc",
	"bitcoin_wallet",
	"eth_htlc",
	"ganache_rust_web3",
	"ethereum_wallet",
]
