[workspace]

members = [
    "application/comit_node",
    "application/comit_node_client",
    "application/comit_wallet",
    "application/ethereum_wallet",
    "application/ledger_query_service",
    "vendor/bitcoin_rpc_test_helpers",
    "vendor/bitcoin_support",
    "vendor/bitcoin_witness",
    "vendor/ethereum_support",
    "vendor/event_store",
    "vendor/key_gen",
    "vendor/lightning_rpc",
    "vendor/secp256k1_support",
    "vendor/tc_bitcoincore_client",
    "vendor/tc_web3_client",
    "vendor/transport_protocol",
]

[replace]
"web3:0.4.0" = { git = "https://github.com/coblox/rust-web3", branch = "to-for-contract-deploy" }
