version: '3'
services:
  eth:
    image: parity/parity:v2.1.3
    command: --config dev --jsonrpc-apis=all --unsafe-expose --tracing=on --logging=debug,ethcore-miner=trace,miner=trace,rpc=trace,tokio_core=warn,tokio_reactor=warn
    ports:
      - "8545:8545"

  btc:
    image: ruimarinho/bitcoin-core:0.17.0-alpine
    command:
      -regtest
      -server
      -printtoconsole
      -rpcbind=0.0.0.0:18443
      -rpcauth=bitcoin:cb77f0957de88ff388cf817ddbc7273$$9eaa166ace0d94a29c6eceb831a42458e93faeb79f895a7ee4ce03f4343f8f55
      -rpcallowip=0.0.0.0/0
      -debug=1
      -zmqpubrawblock=tcp://*:28332
      -zmqpubrawtx=tcp://*:28333
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
    networks:
      - lnd_network

  lnbtc:
    image: coblox/lnd:0.5.1-beta
    environment:
      - NETWORK=regtest
      - CHAIN=bitcoin
      - DEBUG=debug
      - BACKEND=bitcoind
      - BACKEND_RPC_USER=bitcoin
      - BACKEND_RPC_PASS=54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg=
      - BACKEND_RPC_HOST=btc:18443
    entrypoint:
      - "./wait-for-backend.sh"
      - "./start-lnd.sh"
      - "--rpclisten=0.0.0.0:10009"
      - "--bitcoind.zmqpubrawblock=tcp://btc:28332"
      - "--bitcoind.zmqpubrawtx=tcp://btc:28333"
      - "--bitcoin.defaultchanconfs=1"
    ports:
      - "127.0.0.1:10009:10009/tcp"
    container_name: lnd-alice
    depends_on:
      - btc
      - lnd-bob
    networks:
      - lnd_network

  lnd-bob:
    image: coblox/lnd:0.5.1-beta
    environment:
      - NETWORK=regtest
      - CHAIN=bitcoin
      - DEBUG=debug
      - BACKEND=bitcoind
      - BACKEND_RPC_USER=bitcoin
      - BACKEND_RPC_PASS=54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg=
      - BACKEND_RPC_HOST=btc:18443
    entrypoint:
      - "./wait-for-backend.sh"
      - "./start-lnd.sh"
      - "--rpclisten=0.0.0.0:10019"
      - "--bitcoind.zmqpubrawblock=tcp://btc:28332"
      - "--bitcoind.zmqpubrawtx=tcp://btc:28333"
      - "--bitcoin.defaultchanconfs=1"
    ports:
      - "127.0.0.1:10019:10019/tcp"
    container_name: lnd-bob
    depends_on:
      - btc
    networks:
      - lnd_network

networks:
  # a virtual network to be shared between the nodes
  lnd_network:
