[ledger.bitcoin]
docker = "btc"
rpc_url = "http://localhost:18443"
rpc_username = "bitcoin"
rpc_password = "54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg="
up_time = "10000"
down_time = "2000"

[ledger.ethereum]
docker = "eth"
rpc_url = "http://localhost:8545"
up_time = "10000"
down_time = "15000"

[comit_node.alice]
host = "127.0.0.1"
config_dir = "./regtest/alice/"

[comit_node.bob]
host = "127.0.0.1"
config_dir = "./regtest/bob/"

[ledger_query_service.main.env]
LEDGER_QUERY_SERVICE_CONFIG_PATH = "./regtest/ledger_query_service"
ETHEREUM_POLLING_TIME_SEC = "1"
RUST_LOG = "warn,ledger_query_service=debug,warp=info"
