ledgers = ["bitcoin"]

[btsieve.main]
host = "127.0.0.1"

[btsieve.main.env]
BTSIEVE_CONFIG_PATH = "./api_tests/regtest/btsieve/bitcoin_only"
ETHEREUM_POLLING_TIME_SEC = "1"
RUST_LOG = "btsieve=debug,warp=debug,btsieve::api"
