[package]
name = "ganp"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]
[dependencies]
transport_protocol = { path = "../../vendor/transport_protocol" }
bitcoin_support = { path = "../../vendor/bitcoin_support" }
secp256k1_support = { path = "../../vendor/secp256k1_support" }
ethereum_support = { path = "../../vendor/ethereum_support" }
common_types = { path = "../common_types" }
log = "0.4"
serde = "1"
serde_derive = "1"
bitcoin_rpc_client = "0.1"

[dev-dependencies]
memsocket = "0.1"
pretty_env_logger = "0.2"
tokio = "0.1"
maplit = "1"
serde_json = "1"
futures = "0.1"
spectral = "0.6"
hex = "0.3.2"
