[bitcoin]
node_url = "http://localhost:18443"
zmq_endpoint = "tcp://127.0.0.1:28332"

[bitcoin.authentication.cookie]
file_path = "/home/bitcoin/.bitcoin/regtest/.cookie"

[http_api]
address_bind="0.0.0.0"
port_bind=8080
external_url="http://localhost:8080/"
