[package]
name = "bitcoin_rpc_test_helpers"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
bitcoin_support = { path = "../bitcoin_support" }
bitcoincore-rpc = "0.8.0-rc1"
testcontainers = "0.7"
