[network]
listen = ["/onion3/r4nttccifklkruvrztwxuhk2iy4xx7cnnex2sgogbo4zw6rnx3cq2bid:9939"]
use_tor = true

[http_api]
socket = "127.0.0.1:8000"

[http_api.cors]
allowed_origins = "none"

[data]
dir = "/home/tobin/.local/share/comit"

[logging]
level = "Info"

[bitcoin]
network = "regtest"

[bitcoin.bitcoind]
node_url = "http://localhost:18443/"

[ethereum]
chain_id = 1337

[ethereum.geth]
node_url = "http://localhost:8545/"

[lightning]
network = "regtest"

[lightning.lnd]
rest_api_url = "https://localhost:8080/"
dir = "/home/tobin/.lnd"
