[package]
name = "ethereum_htlc"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]

[dependencies]
ethereum_support = { path = "../../vendor/ethereum_support" }
hex = "0.3.2"
ganache_rust_web3 = { path = "../../vendor/ganache_rust_web3" }
common_types = { path = "../common_types" }
log = "0.4.3"
chrono = "0.4.2"
env_logger = "0.5.10"
serde = "1.0.66"
serde_derive = "1.0.66"

[build-dependencies]
regex = "1.0.0"

[dev-dependencies]
tc_trufflesuite_ganachecli = { git = "https://github.com/coblox/testcontainers-rs" }
tc_web3_client = { path = "../../vendor/tc_web3_client" }
testcontainers = { git = "https://github.com/coblox/testcontainers-rs" }
