version: '3'
services:

  # btc is an image of bitcoin node which used as base image for btcd and
  # btccli. The environment variables default values determined on stage of
  # container start within starting script.
  btcd:
    image: btcd
    build:
      context: btcd/
    volumes:
    - shared:/rpc
    - bitcoin:/data
    environment:
    - RPCUSER
    - RPCPASS
    - NETWORK
    - DEBUG
    - MINING_ADDRESS
    networks:
    - lnd-network
    container_name: btcd
    entrypoint: ["./start-btcd.sh"]

  btcctl:
    image: btcd
    build:
      context: btcd/
    volumes:
    - shared:/rpc
    - bitcoin:/data
    environment:
    - RPCUSER
    - RPCPASS
    - NETWORK
    - DEBUG
    - BTCSERVER=btcd
    networks:
    - lnd-network
    container_name: btcctl
    entrypoint: ["./start-btcctl.sh"]

  lnd-alice:
    image: lnd
    build:
      context: lnd
    environment:
    - RPCUSER
    - RPCPASS
    - NETWORK
    - CHAIN
    - DEBUG
    - BTCSERVER=btcd
    volumes:
    - shared:/rpc
    entrypoint:
    - "./start-lnd.sh"
    - "--rpclisten=0.0.0.0:10009"
    ports:
    - "127.0.0.1:10009:10009/tcp"
    container_name: lnd-alice
    depends_on:
      - btcd
    networks:
    - lnd-network

  lnd-bob:
    image: lnd
    build:
      context: lnd
    environment:
    - RPCUSER
    - RPCPASS
    - NETWORK
    - CHAIN
    - DEBUG
    - BTCSERVER=btcd
    volumes:
    - shared:/rpc
    entrypoint:
    - "./start-lnd.sh"
    - "--rpclisten=0.0.0.0:10009"
    ports:
    - "127.0.0.1:10010:10009/tcp"
    container_name: lnd-bob
    depends_on:
      - btcd
    networks:
    - lnd-network

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local


networks:
  # a virtual network to be shared between the nodes
  lnd-network:
