version: '3'
services:

  # btc is an image of bitcoin node which used as base image for btcd and
  # btccli. The environment variables default values determined on stage of
  # container start within starting script.
  btc:
    image: btcd
    build:
      context: btcd/
    volumes:
    - shared:/rpc
    - bitcoin:/data
    environment:
    - RPCUSER
    - RPCPASS
    - NETWORK
    - DEBUG
    - MINING_ADDRESS
    entrypoint: ["./start-btcd.sh"]

  lnd:
    image: lnd
    build:
      context: ./
      dockerfile: lnd/Dockerfile
    environment:
    - RPCUSER
    - RPCPASS
    - NETWORK
    - CHAIN
    - DEBUG
    volumes:
    - shared:/rpc
    entrypoint:
    - "./start-lnd.sh"
    - "--rpclisten=0.0.0.0:10009"
    - "--no-macaroons"
    ports:
    - "127.0.0.1:10009:10009/tcp"
    container_name: lnd_btc
    links:
    - "btc:blockchain"

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local