[package]
name = "swap_log"
version = "0.1.0"
authors = [
    "Franck Royer <franck@coblox.tech>",
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>"
]

[dependencies]
chrono = "0.4.4"
fern = { version = "0.5.6", features = ["colored"] }
log = "0.4.3"

