version: '3'
services:
  comit_node_bob:
    build: ../../
    env_file:
      - "$SWAP_ENV/mainnet.env"
      - ./network.env
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,exchange_service=debug,bitcoin_htlc=debug
      - RUST_BACKTRACE=1
    ports:
    - "8010:8000"
    depends_on:
  comit_node_alice:
    build: ../../
    env_file:
      - "$SWAP_ENV/mainnet.env"
      - ./network.env
    environment:
      - COMIT_NODE_URL=http://exchange_service:8000
      - ROCKET_ADDRESS=0.0.0.0
      - RUST_LOG=info,trading_service=debug,bitcoin_htlc=debug
      - RUST_BACKTRACE=1
    ports:
    - "8000:8000"
