[comit]
comit_listen = "0.0.0.0:8001"
secret_seed = "f87165e305b0f7c4824d3806434f9d0909610a25641ab8773cf92a48c9d77670"

[http_api]
address="0.0.0.0"
port=8000

[web_gui]
address="0.0.0.0"
port=8080

[btsieve]
url = "http://localhost:8181"

[btsieve.bitcoin]
poll_interval_secs = 1
network = "regtest"

[btsieve.ethereum]
poll_interval_secs = 1
network = "regtest"
