version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    ignored_updates:
      # as per https://github.com/comit-network/comit-rs/issues/1316
      - match:
          dependency_name: "primitive-types"
      - match:
          dependency_name: "rlp"
      # we only depend on ethbloom to access certain types. our version needs to match whichever version web3 is transitively bringing in
      - match:
          dependency_name: "ethbloom"
  - package_manager: "javascript"
    directory: "/api_tests"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
