version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
    ignored_updates:
      # we only depend on `libsqlite3-sys` directly to activate the "bundled" feature. the version we are using has to match the one that diesel is depending on, hence bumping it manually is pointless.
      - match:
          dependency_name: "libsqlite3-sys"
      # this needs updating based on the futures_codec version
      - match:
          dependency_name: "bytes"
  - package_manager: "javascript"
    directory: "/api_tests"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
