[package]
name = "ethereum_support"
version = "0.1.0"
authors = ["Thomas Eizinger <thomas@eizinger.io>"]

[dependencies]
web3 = "0.3.0"
secp256k1_support = { path = "../secp256k1_support" }
tiny-keccak = "1.4.2"

[dev-dependencies]
hex = "0.3.2"
secp256k1 = "0.9.2"
