[comit]
remote_comit_node_url = "0.0.0.0:8010"
comit_listen = "0.0.0.0:8011"

[ledger_query_service]
url = "http://localhost:8001"
[ledger_query_service.bitcoin]
poll_interval_secs = 300
[ledger_query_service.ethereum]
poll_interval_secs = 20

[http_api]
address="0.0.0.0"
port=8000
logging=true
