# This file only works in combination with an additional keyfile, e.g. in development.toml
[ethereum]
network_id = 1
node_url = "http://localhost:8545"

[bitcoin]
network = "regtest"
satoshi_per_byte = 50 # used for calculating transaction fees
node_url = "http://localhost:18443"
node_username = "bitcoin"
node_password = "54pLR_f7-G6is32LP-7nbhzZSbJs_2zSATtZV_r05yg="

[lightning_bitcoin]
network = "regtest"
node_uri = "127.0.0.1:10009"
tls_cert_path = "~/.lnd/tls.cert"
readonly_macaroon_path = "~/.lnd/data/chain/bitcoin/regtest/readonly.macaroon"
grpc_origin_url = "http://127.0.0.1"

[comit]
remote_comit_node_url = "0.0.0.0:8010"
comit_listen = "0.0.0.0:8011"

[ledger_query_service]
url = "http://localhost:8001"
[ledger_query_service.bitcoin]
poll_interval_secs = 300
[ledger_query_service.ethereum]
poll_interval_secs = 20

[http_api]
address="0.0.0.0"
port=8000
logging=true
