[comit]
remote_comit_node_url = "0.0.0.0:8010"
comit_listen = "0.0.0.0:8011"
secret_seed = "c1fd6fc5bde7fee2c2fb6d868dc0f40368051fede1d83f814839d562c210aa27"

[btsieve]
url = "http://localhost:8001"
[btsieve.bitcoin]
poll_interval_secs = 300
network = "regtest"

[btsieve.ethereum]
poll_interval_secs = 20
network = "regtest"

[http_api]
address="0.0.0.0"
port=8000

[web_gui]
address="0.0.0.0"
port=8080
