[comit]
remote_comit_node_url = "0.0.0.0:8010"
comit_listen = "0.0.0.0:8011"
secret_seed = "c1fd6fc5bde7fee2c2fb6d868dc0f40368051fede1d83f814839d562c210aa27"

[ledger_query_service]
url = "http://localhost:8001"
[ledger_query_service.bitcoin]
poll_interval_secs = 300
[ledger_query_service.ethereum]
poll_interval_secs = 20

[http_api]
address="0.0.0.0"
port=8000
logging=true
