[package]
name = "secp256k1_omni_context"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
edition = "2018"

[dependencies]
lazy_static = "1"
secp256k1 = { version = "0.12", features = ["rand"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
hex = "0.4.0"
serde_json = "1"
