[package]
name = "comit_node_client"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]

[dependencies]
bitcoin_rpc_client = "0.4"
bitcoin_support = { path = "../../vendor/bitcoin_support" }
ethereum_support = { path = "../../vendor/ethereum_support" }
lazy_static = "1"
maplit = "1"
regex = "1"
reqwest = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
structopt = "0.2"
uuid = { version = "0.6", features = ["serde", "v4"] }
