[package]
name = "comit_node_client"
version = "0.1.0"
authors = [
    "Thomas Eizinger <thomas@coblox.tech>",
    "Philipp Hoenisch <philipp@coblox.tech>",
    "Franck Royer <franck@coblox.tech>",
    "Lloyd Fournier <lloyd@coblox.tech>",
]

[dependencies]
structopt = "0.2.8"
serde = "1.0.64"
serde_json = "1.0.19"
serde_derive = "1.0.63"
reqwest = "0.9"
lazy_static = "1"
regex = "1.0.0"
uuid = { version = "0.6.3", features = ["serde", "v4"] }
bitcoin_rpc_client = "0.3"
maplit = "1"

ethereum_support = { path = "../../vendor/ethereum_support" }
bitcoin_support = { path = "../../vendor/bitcoin_support" }
