[bitcoin]
transient_root_key="tprv8ZgxMBicQKsPcsbCVeqqF1KVdH7gwDJbxbzpCxDUsoXHdb6SnTPYxdwSAKhjQEcrsZTSsJWvjX4XvtRLPMq3q5xKqoW1A5p3RBmwDLdFZ5J"

[comit]
remote_comit_node_url = "127.0.0.1:8001"
comit_listen = "0.0.0.0:8011"

[http_api]
address="0.0.0.0"
port=8010
logging=true

[ledger_query_service]
url = "http://localhost:8080"
[ledger_query_service.bitcoin]
poll_interval_secs = 1
[ledger_query_service.ethereum]
poll_interval_secs = 1

