ledgers = ["ethereum"]

[btsieve.main]
host = "127.0.0.1"
config_dir = "./api_tests/regtest/btsieve/ethereum_only"

[btsieve.main.env]
ETHEREUM_POLLING_TIME_SEC = "1"
RUST_LOG = "btsieve=debug,warp=debug,btsieve::api"
