[package]
name = "comit_node"
version = "0.1.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]

[dependencies]
bitcoin_rpc_client = "0.4"
bitcoin_rpc_test_helpers = { path = "../../vendor/bitcoin_rpc_test_helpers" }
bitcoin_support = { path = "../../vendor/bitcoin_support"}
bitcoin_witness = { path = "../../vendor/bitcoin_witness" }
chrono = "0.4"
config = "0.9"
debug_stub_derive = "0.3"
ethereum_support = { path = "../../vendor/ethereum_support" }
event_store = { path = "../../vendor/event_store" }
failure = "0.1"
fern = { version = "0.5", features = ["colored"] }
futures = "0.1"
hex = "0.3"
http-api-problem = "0.9"
http = "0.1"
hyper = "0.12"
lazy_static = "1"
log = "0.4"
mime = "0.3"
rand = "0.4"
reqwest = "0.9"
rlp = "0.2"
rust-crypto = "0.2"
rustc-hex = "1"
secp256k1_support = { path = "../../vendor/secp256k1_support" }
serde = "1"
serde_derive = "1"
serde_json = "1"
state_machine_future = { git = "https://github.com/coblox/state_machine_future.git", branch = "master" }
tc_bitcoincore_client = { path = "../../vendor/tc_bitcoincore_client" }
tiny-keccak = "1.4"
tokio = "0.1"
tokio-timer = "0.2"
bam = { path = "../../vendor/bam" }
url = "1.7"
uuid = { version = "0.6", features = ["serde", "v4"] }
warp = "0.1"

[dev-dependencies]
key_gen = { path = "../../vendor/key_gen"}
lazy_static = "1"
maplit = "1"
memsocket = "0.1"
pretty_env_logger = "0.2"
spectral = "0.6"
tc_web3_client = { path = "../../vendor/tc_web3_client" }
testcontainers = "0.3"

[build-dependencies]
regex = "1"
