ledgers = ["bitcoin", "ethereum"]

[comit_node.alice]
host = "127.0.0.1"
config_dir = "./api_tests/regtest/alice/"

[comit_node.bob]
host = "127.0.0.1"
config_dir = "./api_tests/regtest/bob/"

[btsieve.main.env]
BTSIEVE_CONFIG_PATH = "./api_tests/regtest/btsieve"
ETHEREUM_POLLING_TIME_SEC = "1"
RUST_LOG = "warn,btsieve=debug,warp=info"
