ledgers = ["bitcoin", "ethereum"]

[cnd.alice]
host = "127.0.0.1"
config_file = "./api_tests/regtest/alice/cnd.toml"

[cnd.bob]
host = "127.0.0.1"
config_file = "./api_tests/regtest/bob/cnd.toml"

[btsieve.main]
config_file = "./api_tests/regtest/btsieve/btsieve.toml"
env = { RUST_LOG = "warn,btsieve=debug,warp=info" }
