name: Compile Binary for ARM

on:
  push:
    branches:
      - 'staging'
      - 'trying'
      - 'master'
      - 'dev'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          # The registry cache is useful as long as we need the same dependencies as another job, regardless of the Rust version and operating system.
          key: cargo-registry-${{ hashFiles('Cargo.lock') }}-v3

      - name: Cache cargo binaries
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          # The cargo binary cache is useful as long as we use the same Rust version and operating system, but regardless of our dependencies.
          key: ubuntu-latest-cargo-binaries-${{ steps.toolchain.outputs.rustc_hash }}-v2

      - name: Cache target directory
        uses: actions/cache@v2
        with:
          path: target
          # The target directory is only useful with the same Rust version, dependencies and operating system.
          key: ubuntu-latest-target-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.lock') }}-build-v3

      - name: Setup cross-compilation environment
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf
          echo -e "[target.armv7-unknown-linux-gnueabihf]\nlinker = \"arm-linux-gnueabihf-gcc\"" >> ~/.cargo/config

      - name: Build cnd
        run: cargo build --target=armv7-unknown-linux-gnueabihf -p cnd

      - name: Build nectar
        run: cargo build --target=armv7-unknown-linux-gnueabihf -p nectar

      - name: Upload cnd archive that contains the cnd binary
        uses: actions/upload-artifact@v1
        with:
          name: cnd
          path: target/armv7-unknown-linux-gnueabihf/debug/cnd

      - name: Upload nectar archive that contains the nectar binary
        uses: actions/upload-artifact@v1
        with:
          name: nectar
          path: target/armv7-unknown-linux-gnueabihf/debug/nectar
