name: CI

on:
  push:
    branches:
      - 'staging'
      - 'trying'
      - 'master'
      - 'dev'
  pull_request:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Install NodeJS 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          # The registry cache is useful as long as we need the same dependencies as another job, regardless of the Rust version and operating system.
          key: cargo-registry-${{ hashFiles('Cargo.lock') }}-v2

      - name: Cache cargo binaries
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          # The cargo binary cache is useful as long as we use the same Rust version but regardless of our dependencies.
          key: ubuntu-latest-cargo-binaries-${{ steps.toolchain.outputs.rustc_hash }}-v2

      - name: Cache target directory
        uses: actions/cache@v2
        with:
          path: target
          # The target directory is only useful with the same Rust version, dependencies and operating system.
          key: ubuntu-latest-target-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.lock') }}-clippy-v2

      - name: Check formatting
        run: make check_format

      - name: Run linter
        run: make clippy

  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            e2e: true
            bin-suffix: ""
          - os: macos-latest
            e2e: true
            bin-suffix: ""
          - os: windows-latest
            e2e: true
            bin-suffix: .exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          # The registry cache is useful as long as we need the same dependencies as another job, regardless of the Rust version and operating system.
          key: cargo-registry-${{ hashFiles('Cargo.lock') }}-v3

      - name: Cache cargo binaries
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          # The cargo binary cache is useful as long as we use the same Rust version and operating system, but regardless of our dependencies.
          key: ${{ matrix.os }}-cargo-binaries-${{ steps.toolchain.outputs.rustc_hash }}-v2

      - name: Cache target directory
        uses: actions/cache@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          path: target
          # The target directory is only useful with the same Rust version, dependencies and operating system.
          key: ${{ matrix.os }}-target-${{ steps.toolchain.outputs.rustc_hash }}-${{ hashFiles('Cargo.lock') }}-build-v3

      - name: Build ${{ matrix.os }} binary
        run: make build

      - name: Build docs
        run: make doc

      - name: Run unit tests (with docker)
        if: matrix.os == 'ubuntu-latest'
        run: make test

      - name: Run unit tests (no docker)
        if: matrix.os != 'ubuntu-latest'
        shell: bash
        run: |
          (cd ./comit; cargo test --no-default-features)
          (cd ./cnd; cargo test --no-default-features)
          (cd ./nectar; cargo test --no-default-features)

      # We've ran `cargo build --all-targets` earlier, that is different to from just building the binary.
      # Our e2e tests lazily re-build the binaries, that can timeout our tests so build them here in advance.
      - name: Build binaries for e2e test
        if: matrix.e2e
        run: |
          cargo build -p cnd
          cargo build -p nectar

      - name: Upload cnd-${{ matrix.os }} archive that contains the cnd binary
        if: matrix.e2e
        uses: actions/upload-artifact@v1
        with:
          name: cnd-${{ matrix.os }}
          path: target/debug/cnd${{ matrix.bin-suffix }}

      - name: Upload nectar-${{ matrix.os }} archive that contains the nectar binary
        if: matrix.e2e
        uses: actions/upload-artifact@v1
        with:
          name: nectar-${{ matrix.os }}
          path: target/debug/nectar${{ matrix.bin-suffix }}

      - name: Install NodeJS 14.x
        if: matrix.e2e
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache node_modules directory
        if: matrix.e2e
        uses: actions/cache@v2
        with:
          path: tests/node_modules
          key: ${{ matrix.os }}-node-14-node-modules-directory-${{ hashFiles('tests/package.json') }}

      - name: Run e2e tests
        if: matrix.e2e
        shell: bash
        run: |
          export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
          cd tests
          yarn install
          yarn test

      - name: Upload bitcoind log
        if: matrix.e2e && failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.os }}-e2e-logs-bitcoind.log
          path: tests/log/bitcoind/regtest/debug.log

      - name: Upload parity log
        if: matrix.e2e && failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.os }}-e2e-logs-parity.log
          path: tests/log/parity/parity.log

      - name: Upload lnd logs
        if: matrix.e2e && failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.os }}-e2e-logs-lnd
          path: tests/log/lnd-*/logs/bitcoin/regtest/lnd.log

      - name: Upload e2e logs
        if: matrix.e2e && failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ matrix.os }}-e2e-test-logs
          path: tests/log/tests/
