name: CI

on:
  pull_request:
  push:
    branches:
      - 'staging'
      - 'trying'
      - 'master'

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Cache ~/.cargo/bin directory
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ubuntu-rust-${{ steps.toolchain.outputs.rustc_hash }}-cargo-bin-directory-v2

      - name: Install tomlfmt
        run: which cargo-tomlfmt || cargo install cargo-tomlfmt

      - name: Check Cargo.toml formatting
        run: cargo tomlfmt -d -p Cargo.toml

      - name: Check code formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

  build_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          override: true

      - name: Cache target directory
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.os }}-rust-${{ steps.toolchain.outputs.rustc_hash }}-target-directory-${{ hashFiles('Cargo.lock') }}-v5

      - name: Cache ~/.cargo/registry directory
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.os }}-rust-${{ steps.toolchain.outputs.rustc_hash }}-cargo-registry-directory-${{ hashFiles('Cargo.lock') }}-v5

      - name: Cargo check ${{ matrix.os }}
        run: cargo check

      - name: Cargo test
        if: matrix.os != 'macos-latest'
        run: cargo test

      - name: Cargo test without Docker
        if: matrix.os == 'macos-latest'
        run: cargo test --no-default-features

      - name: Build the binary for ${{ matrix.os }}
        run: cargo build --bin nectar

      - name: Upload cnd-${{ matrix.os }} archive that contains the binary
        uses: actions/upload-artifact@v1
        with:
          name: nectar-${{ matrix.os }}
          path: target/debug/nectar
