name: CI

on:
  push:
    branches-ignore:
      - 'staging.tmp'
      - 'trying.tmp'

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Extract toolchain version from rust-toolchain
        run: echo "::set-env name=RUST_TOOLCHAIN::$(cat rust-toolchain)"

      - name: Install ${{ env.RUST_TOOLCHAIN }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - name: Cache ~/.cargo/bin directory
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ubuntu-rust-${{ env.RUST_TOOLCHAIN }}-cargo-bin-directory

      - name: Check formatting
        run: make check_format

      - name: Run linter
        run: make clippy

  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Extract toolchain version from rust-toolchain
        run: echo "::set-env name=RUST_TOOLCHAIN::$(cat rust-toolchain)"

      - name: Install ${{ env.RUST_TOOLCHAIN }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true

      - name: Cache target directory
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.os }}-rust-${{ env.RUST_TOOLCHAIN }}-v2-target-directory-${{ hashFiles('Cargo.lock') }}

      - name: Cache ~/.cargo/registry directory
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.os }}-rust-${{ env.RUST_TOOLCHAIN }}-cargo-registry-directory-${{ hashFiles('Cargo.lock') }}

      - name: Build ${{ matrix.os }} binary
        run: make build

      - name: Build docs
        run: make doc

      # Ignore tests on macos due to missing docker
      - name: Run unit tests
        if: matrix.os != 'macos-latest'
        run: make test

      - name: Upload cnd-${{ matrix.os }} archive that contains the cnd binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v1
        with:
          name: cnd-${{ matrix.os }}
          path: target/debug/cnd

  e2e_test:
    strategy:
      # Do not cancel ubuntu even if macos fails
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download cnd-${{ matrix.os }} archive and extract cnd binary
        uses: actions/download-artifact@v1
        with:
          name: cnd-${{ matrix.os }}
          path: target/debug/

      - name: Fix missing executable permission
        run: |
          chmod a+x target/debug/cnd

      - name: Install NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node_modules directory
        uses: actions/cache@v1
        with:
          path: api_tests/node_modules
          key: ${{ matrix.os }}-node-modules-directory-${{ hashFiles('api_tests/package.json') }}

      - name: Run e2e tests
        run: |
          export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
          cd api_tests
          yarn install
          yarn ci

      - name: Upload bitcoind log
        if: failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: e2e-logs-bitcoind.log
          path: api_tests/log/bitcoind/regtest/debug.log

      - name: Upload parity log
        if: failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: e2e-logs-parity.log
          path: api_tests/log/parity/parity.log

      - name: Upload lnd logs
        if: failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: e2e-logs-lnd
          path: api_tests/log/lnd-*/logs/bitcoin/regtest/lnd.log

      - name: Upload e2e logs
        if: failure()
        uses: actions/upload-artifact@v2-preview
        with:
          name: e2e-test-logs
          path: api_tests/log/tests/
