name: "Merge release branch into dev"

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  merge_release_into_dev:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') # only merged release branches must trigger this
    name: Merge release-branch back into dev
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request for merging master back into dev
        uses: thomaseizinger/create-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.BOTTY_GITHUB_TOKEN }}
          head: master
          base: dev
          title: Merge `master` into `dev`
          body: |
            This PR merges the `master` branch back into `dev`.
            This happens to ensure that the updates that happend on the release branch, i.e. CHANGELOG and manifest updates are also present on the dev branch.
            Otherwise, GitHub will "complain" that the next release branch is not up to date with master because it is missing the merge commit from the last release.
