name: "Release cnd"

on:
  release:
    types: [created]

env:
  CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc

jobs:
  release:
    if: startsWith(github.event.release.tag_name, 'cnd-') # only trigger this if we released cnd
    name: Release cnd
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, x86_64-apple-darwin, x86_64-pc-windows-gnu ]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            docker: true
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-gnu
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout tagged commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          token: ${{ secrets.BOTTY_GITHUB_TOKEN }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Install compiler for armhf arch
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabihf

      - name: Build ${{ matrix.target }} release binary
        id: build
        run: cargo build --target=${{ matrix.target }} --release --package cnd

      - name: Extract version from tag name
        id: extract-version
        uses: ./.github/actions/trim-front
        with:
          string: ${{ github.event.release.tag_name }}
          prefix: cnd-

      # Remove once python 3 is the default
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Create release archive
        id: create-archive
        uses: ./.github/actions/create-release-archive
        with:
          binary: cnd
          version: ${{ steps.extract-version.outputs.trimmed }}
          target: ${{ matrix.target }}

      - name: Upload ${{ matrix.os }} release binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BOTTY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.create-archive.outputs.archive }}
          asset_name: ${{ steps.create-archive.outputs.archive }}
          asset_content_type: application/gzip

      - name: Check if publication to docker should be done
        id: check-docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        run: |
          echo "::set-output name=process::${{ env.DOCKER_USERNAME != '' && matrix.docker }}"

      - name: Login to docker
        if: steps.check-docker.outputs.process == true
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build cnd docker image as ${{ steps.extract-version.outputs.trimmed }} and latest
        if: steps.check-docker.outputs.process == true
        run: |
          VERSION="${{ steps.extract-version.outputs.trimmed }}"
          docker build . -t comitnetwork/cnd:$VERSION -t comitnetwork/cnd:latest

      - name: Test docker image by starting it and curling the cnd API
        if: steps.check-docker.outputs.process == true
        run: |
          VERSION="${{ steps.extract-version.outputs.trimmed }}"
          echo "::starting docker-container comitnetwork/cnd:$VERSION"
          docker run --publish 8000:8000 --detach --name cnd_container comitnetwork/cnd:$VERSION
          curl --fail localhost:8000/
          echo "::cnd API curled successfully"
          docker stop cnd_container

      - name: Publish docker image as ${{ steps.extract-version.outputs.trimmed }} and latest
        if: steps.check-docker.outputs.process == true
        run: |
          VERSION="${{ steps.extract-version.outputs.trimmed }}"
          docker push comitnetwork/cnd:$VERSION
          docker push comitnetwork/cnd:latest
